In [13]:
from tensorflow.keras.preprocessing.text import one_hot


In [14]:
sentences=[
    'I love my dog',
    'I love my cat',
    'ArithmeticError',
    'ye misal paav khayla',
    'yeto ka vada paav khayla',
]

In [15]:
#defining vocabulary size
voc_size=10000


In [16]:
#ohe representation
onehot_repr=[one_hot(words,voc_size) for words in sentences]
onehot_repr

[[2621, 7642, 6427, 3733],
 [2621, 7642, 6427, 3502],
 [7723],
 [5570, 8680, 335, 4779],
 [1893, 1472, 3659, 335, 4779]]

In [17]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
 

In [18]:
import numpy as np


In [19]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2621 7642 6427 3733]
 [   0    0    0    0 2621 7642 6427 3502]
 [   0    0    0    0    0    0    0 7723]
 [   0    0    0    0 5570 8680  335 4779]
 [   0    0    0 1893 1472 3659  335 4779]]


In [20]:
#feature representation
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=8))
model.compile('adam','mse')
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


array([[[-3.5515390e-02, -3.9454378e-02,  8.1669539e-05, -9.8756552e-03,
          3.7809204e-02, -1.3397157e-02,  4.2717565e-02, -1.3304520e-02,
         -2.1895349e-02, -3.1569377e-02],
        [-3.5515390e-02, -3.9454378e-02,  8.1669539e-05, -9.8756552e-03,
          3.7809204e-02, -1.3397157e-02,  4.2717565e-02, -1.3304520e-02,
         -2.1895349e-02, -3.1569377e-02],
        [-3.5515390e-02, -3.9454378e-02,  8.1669539e-05, -9.8756552e-03,
          3.7809204e-02, -1.3397157e-02,  4.2717565e-02, -1.3304520e-02,
         -2.1895349e-02, -3.1569377e-02],
        [-3.5515390e-02, -3.9454378e-02,  8.1669539e-05, -9.8756552e-03,
          3.7809204e-02, -1.3397157e-02,  4.2717565e-02, -1.3304520e-02,
         -2.1895349e-02, -3.1569377e-02],
        [-2.1669341e-02,  3.9906409e-02,  2.7155843e-02, -3.1850208e-02,
         -4.3889701e-02,  3.1850640e-02,  1.4273524e-03, -2.0042693e-02,
          4.2027842e-02, -3.6431707e-02],
        [-4.8985984e-02,  4.6261344e-02, -2.7480448e-02,  1.

In [25]:
print(embedded_docs[0])

[   0    0    0    0 2621 7642 6427 3733]
